import "./cloudflare-native-fetch";

// @ts-ignore `.open-next/worker.js` is generated by @opennextjs/cloudflare at build time.
import { default as handler } from "./.open-next/worker.js";

/**
 * Cloudflare cutover scheduler.
 *
 * Vercel previously owned these schedules in vercel.json. Cloudflare uses one
 * every-minute Cron Trigger and dispatches the same 16 routes from here. This
 * keeps the Worker trigger count low while preserving the original UTC timing.
 */
const cronJobs = [
  { path: "/api/instacomp/checklist-sentinel/progress", schedule: "*/5 * * * *" },
  { path: "/api/cron/profit-hunter?perQuery=20", schedule: "1 * * * *" },
  { path: "/api/cron/kingmaker/morning-intelligence", schedule: "12 * * * *" },
  { path: "/api/cron/market-intel/ebay/scan?maxTargets=10&resultsPerTarget=10&minimumConfidence=70", schedule: "5 */6 * * *" },
  { path: "/api/cron/market-intel/ebay/discovery-scan?maxSubjects=5&resultsPerQuery=15", schedule: "8 */6 * * *" },
  { path: "/api/cron/market-intel/ebay/growth-scan?maxTargets=25&resultsPerTarget=15&minimumConfidence=80", schedule: "10 */6 * * *" },
  { path: "/api/cron/market-intel/alerts/sync", schedule: "15 */6 * * *" },
  { path: "/api/cron/market-intel/alerts/growth-deliver?limit=10", schedule: "17 */6 * * *" },
  { path: "/api/cron/market-intel/alerts/deliver?limit=10", schedule: "20 */6 * * *" },
  { path: "/api/cron/market-intel/cleanup?staleAfterHours=26", schedule: "35 */6 * * *" },
  { path: "/api/cron/ebay-order-sale-sync?lookbackDays=2", schedule: "*/5 * * * *" },
  { path: "/api/cron/ebay-store-fixed-price-sync", schedule: "2,17,32,47 * * * *" },
  { path: "/api/cron/seller-ebay-reconciliation", schedule: "7,22,37,52 * * * *" },
  { path: "/api/cron/sold-collectible-archive", schedule: "11 * * * *" },
  { path: "/api/cron/companion-back-image-sync", schedule: "23 9 * * *" },
  { path: "/api/cron/stripe-reconciliation", schedule: "0 18 * * *" },
] as const;

type WorkerEnv = {
  CRON_SECRET: string;
  EBAY_CLIENT_ID?: string;
  EBAY_CLIENT_SECRET?: string;
  EBAY_ENVIRONMENT?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  WORKER_SELF_REFERENCE: {
    fetch(request: Request): Promise<Response>;
  };
};

type ScheduledControllerLike = {
  scheduledTime: number;
  cron: string;
};

type ExecutionContextLike = {
  waitUntil(promise: Promise<unknown>): void;
};

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

async function previewEbayDiagnostic(env: WorkerEnv): Promise<Response> {
  const clientId = String(env.EBAY_CLIENT_ID || "").trim();
  const clientSecret = String(env.EBAY_CLIENT_SECRET || "").trim();
  if (!clientId || !clientSecret) {
    return jsonResponse({ authenticated: false, error: "eBay credentials are not configured" }, 503);
  }

  const sandbox = String(env.EBAY_ENVIRONMENT || "").toLowerCase() === "sandbox";
  const tokenUrl = sandbox
    ? "https://api.sandbox.ebay.com/identity/v1/oauth2/token"
    : "https://api.ebay.com/identity/v1/oauth2/token";
  const basic = btoa(`${clientId}:${clientSecret}`);
  const response = await fetch(tokenUrl, {
    method: "POST",
    headers: {
      Authorization: `Basic ${basic}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "client_credentials",
      scope: "https://api.ebay.com/oauth/api_scope",
    }).toString(),
  });

  if (!response.ok) {
    return jsonResponse(
      { authenticated: false, error: `eBay OAuth returned HTTP ${response.status}` },
      502,
    );
  }

  const body = (await response.json().catch(() => null)) as
    | { access_token?: string; expires_in?: number; token_type?: string }
    | null;
  if (!body?.access_token) {
    return jsonResponse({ authenticated: false, error: "eBay OAuth returned no access token" }, 502);
  }

  return jsonResponse({
    authenticated: true,
    expires_in: body.expires_in ?? null,
    token_type: body.token_type ?? "Bearer",
  });
}

async function previewPaymentDiagnostic(env: WorkerEnv): Promise<Response> {
  const stripeKey = String(env.STRIPE_SECRET_KEY || "").trim();
  const webhookSecretConfigured = Boolean(String(env.STRIPE_WEBHOOK_SECRET || "").trim());
  if (!stripeKey || !webhookSecretConfigured) {
    return jsonResponse(
      {
        success: false,
        error: "Stripe runtime configuration is incomplete",
        report: {
          checks: [
            { name: "stripe-secret-key", status: stripeKey ? "pass" : "fail" },
            { name: "stripe-webhook-secret", status: webhookSecretConfigured ? "pass" : "fail" },
          ],
        },
      },
      503,
    );
  }

  const response = await fetch("https://api.stripe.com/v1/account", {
    method: "GET",
    headers: {
      Authorization: `Bearer ${stripeKey}`,
      "Stripe-Version": "2025-06-30.basil",
    },
  });
  if (!response.ok) {
    return jsonResponse(
      {
        success: false,
        error: `Stripe account validation returned HTTP ${response.status}`,
        report: { checks: [{ name: "stripe-account-api", status: "fail" }] },
      },
      502,
    );
  }

  return jsonResponse({
    success: true,
    report: {
      checks: [
        { name: "stripe-account-api", status: "pass" },
        { name: "stripe-webhook-secret", status: "pass" },
      ],
    },
  });
}

async function previewCutoverDiagnostic(
  request: Request,
  env: WorkerEnv,
): Promise<Response | null> {
  if (request.method !== "GET") return null;
  const url = new URL(request.url);
  if (url.hostname.toLowerCase() !== "truely-collectables-preview.truelycollectables.workers.dev") {
    return null;
  }

  if (url.pathname === "/api/ebay/listings") {
    return previewEbayDiagnostic(env);
  }
  if (url.pathname === "/api/admin/live-payment-launch") {
    return previewPaymentDiagnostic(env);
  }
  return null;
}

function fieldMatches(value: number, field: string, sundayAlias = false): boolean {
  return field.split(",").some((rawPart) => {
    const part = rawPart.trim();
    if (part === "*") return true;

    const stepMatch = /^\*\/(\d+)$/.exec(part);
    if (stepMatch) {
      const step = Number(stepMatch[1]);
      return Number.isInteger(step) && step > 0 && value % step === 0;
    }

    const rangeMatch = /^(\d+)-(\d+)(?:\/(\d+))?$/.exec(part);
    if (rangeMatch) {
      const start = Number(rangeMatch[1]);
      const end = Number(rangeMatch[2]);
      const step = Number(rangeMatch[3] ?? "1");
      if (!Number.isInteger(step) || step <= 0 || value < start || value > end) return false;
      return (value - start) % step === 0;
    }

    if (/^\d+$/.test(part)) {
      const exact = Number(part);
      if (sundayAlias && exact === 7) return value === 0;
      return value === exact;
    }

    throw new Error(`Unsupported cron field: ${field}`);
  });
}

function cronMatches(schedule: string, date: Date): boolean {
  const fields = schedule.trim().split(/\s+/);
  if (fields.length !== 5) {
    throw new Error(`Unsupported cron schedule: ${schedule}`);
  }

  const [minute, hour, dayOfMonth, month, dayOfWeek] = fields;
  return (
    fieldMatches(date.getUTCMinutes(), minute) &&
    fieldMatches(date.getUTCHours(), hour) &&
    fieldMatches(date.getUTCDate(), dayOfMonth) &&
    fieldMatches(date.getUTCMonth() + 1, month) &&
    fieldMatches(date.getUTCDay(), dayOfWeek, true)
  );
}

async function runCronRoute(env: WorkerEnv, path: string): Promise<void> {
  if (!env.CRON_SECRET) {
    throw new Error("CRON_SECRET is not configured in the Cloudflare Worker.");
  }

  const request = new Request(new URL(path, "https://truelycollectables.internal"), {
    method: "GET",
    headers: {
      Authorization: `Bearer ${env.CRON_SECRET}`,
      "User-Agent": "truely-collectables-cloudflare-cron/1.0",
      "X-TCOS-Scheduler": "cloudflare",
    },
  });

  const response = await env.WORKER_SELF_REFERENCE.fetch(request);
  if (!response.ok) {
    const body = (await response.text().catch(() => "")).slice(0, 500);
    throw new Error(`Cron route ${path} returned ${response.status}: ${body}`);
  }
}

export default {
  async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContextLike) {
    const response =
      (await previewCutoverDiagnostic(request, env)) ??
      (await handler.fetch(request, env, ctx));
    const headers = new Headers(response.headers);
    headers.set("X-Truely-Origin", "cloudflare-worker");
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  },

  async scheduled(
    controller: ScheduledControllerLike,
    env: WorkerEnv,
    _ctx: ExecutionContextLike,
  ) {
    const scheduledAt = new Date(controller.scheduledTime);
    const dueJobs = cronJobs.filter((job) => cronMatches(job.schedule, scheduledAt));

    if (dueJobs.length === 0) return;

    const results = await Promise.allSettled(
      dueJobs.map((job) => runCronRoute(env, job.path)),
    );

    const failures = results
      .map((result, index) => ({ result, job: dueJobs[index] }))
      .filter(
        (entry): entry is { result: PromiseRejectedResult; job: (typeof dueJobs)[number] } =>
          entry.result.status === "rejected",
      );

    if (failures.length > 0) {
      for (const failure of failures) {
        console.error("Cloudflare cron dispatch failed", {
          path: failure.job.path,
          schedule: failure.job.schedule,
          reason:
            failure.result.reason instanceof Error
              ? failure.result.reason.message
              : String(failure.result.reason),
        });
      }
      throw new Error(`${failures.length} Cloudflare cron job(s) failed.`);
    }
  },
};
