import "./cloudflare-native-fetch";

// @ts-ignore `.open-next/worker.js` is generated by @opennextjs/cloudflare at build time.
import { default as handler } from "./.open-next/worker.js";

/**
 * Cloudflare cutover scheduler.
 *
 * Cloudflare uses one every-minute Cron Trigger and dispatches the routes
 * from here. Most legacy jobs remain UTC. Owner-facing Deal Hunter jobs use
 * America/Denver so their requested local times stay correct across DST.
 */
const DEAL_HUNTER_TIME_ZONE = "America/Denver";
const DEAL_HUNTER_HOURS = "7,11,15,19,21";
const INCIDENT_DISABLE_SCHEDULED_JOBS = true;

type CronJob = {
  path: string;
  schedule: string;
  timeZone?: string;
};

const cronJobs: readonly CronJob[] = [
  { path: "/api/instacomp/checklist-sentinel/progress", schedule: "*/5 * * * *" },
  {
    path: "/api/cron/profit-hunter?perQuery=20",
    schedule: `0 ${DEAL_HUNTER_HOURS} * * *`,
    timeZone: DEAL_HUNTER_TIME_ZONE,
  },
  { path: "/api/cron/kingmaker/morning-intelligence", schedule: "12 * * * *" },
  {
    path: "/api/cron/market-intel/ebay/scan?maxTargets=10&resultsPerTarget=10&minimumConfidence=70",
    schedule: `2 ${DEAL_HUNTER_HOURS} * * *`,
    timeZone: DEAL_HUNTER_TIME_ZONE,
  },
  {
    path: "/api/cron/market-intel/ebay/discovery-scan?maxSubjects=5&resultsPerQuery=15",
    schedule: `5 ${DEAL_HUNTER_HOURS} * * *`,
    timeZone: DEAL_HUNTER_TIME_ZONE,
  },
  {
    path: "/api/cron/market-intel/ebay/growth-scan?maxTargets=25&resultsPerTarget=15&minimumConfidence=80",
    schedule: `8 ${DEAL_HUNTER_HOURS} * * *`,
    timeZone: DEAL_HUNTER_TIME_ZONE,
  },
  {
    path: "/api/cron/market-intel/alerts/sync",
    schedule: `12 ${DEAL_HUNTER_HOURS} * * *`,
    timeZone: DEAL_HUNTER_TIME_ZONE,
  },
  {
    path: "/api/cron/market-intel/alerts/growth-deliver?limit=10",
    schedule: `14 ${DEAL_HUNTER_HOURS} * * *`,
    timeZone: DEAL_HUNTER_TIME_ZONE,
  },
  {
    path: "/api/cron/market-intel/alerts/deliver?limit=10",
    schedule: `17 ${DEAL_HUNTER_HOURS} * * *`,
    timeZone: DEAL_HUNTER_TIME_ZONE,
  },
  {
    path: "/api/cron/market-intel/cleanup?staleAfterHours=26",
    schedule: `25 ${DEAL_HUNTER_HOURS} * * *`,
    timeZone: DEAL_HUNTER_TIME_ZONE,
  },
  { path: "/api/cron/ebay-order-sale-sync?lookbackDays=2", schedule: "*/5 * * * *" },
  { path: "/api/cron/ebay-store-fixed-price-sync", schedule: "2,17,32,47 * * * *" },
  { path: "/api/cron/seller-ebay-reconciliation", schedule: "7,22,37,52 * * * *" },
  { path: "/api/cron/sold-collectible-archive", schedule: "11 * * * *" },
  { path: "/api/cron/companion-back-image-sync", schedule: "23 9 * * *" },
  { path: "/api/cron/stripe-reconciliation", schedule: "0 18 * * *" },
];

type WorkerEnv = {
  CRON_SECRET: string;
  INSTACOMP_AI_LOCAL_URL?: string;
  INSTACOMP_AI_LOCAL_KEY?: string;
  INSTACOMP_AI_API_KEY?: string;
  WORKER_SELF_REFERENCE: {
    fetch(request: Request): Promise<Response>;
  };
};

type ScheduledControllerLike = {
  scheduledTime: number;
  cron: string;
};

type ExecutionContextLike = {
  waitUntil(promise: Promise<unknown>): void;
};

function withCloudflareOrigin(response: Response) {
  const headers = new Headers(response.headers);
  headers.set("X-Truely-Origin", "cloudflare-worker");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

function readinessJson(payload: Record<string, unknown>, status: number) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "private, no-store, max-age=0",
      "X-Content-Type-Options": "nosniff",
      "X-Truely-Origin": "cloudflare-worker",
    },
  });
}

async function cloudflareInstaCompReadiness(env: WorkerEnv) {
  const baseUrl = String(env.INSTACOMP_AI_LOCAL_URL || "")
    .trim()
    .replace(/\/+$/, "");
  if (!/^https?:\/\//i.test(baseUrl)) {
    return readinessJson(
      {
        ok: false,
        configured: false,
        reachable: false,
        dnsResolved: false,
        internalMemoryReady: false,
        checklistReady: false,
        localModelReady: false,
        runtimeSourceFingerprint: null,
        architecture: ["instacomp_ai"],
        reason: "internal_engine_url_not_configured",
      },
      503,
    );
  }

  const headers = new Headers({ Accept: "application/json" });
  const key = String(env.INSTACOMP_AI_LOCAL_KEY || env.INSTACOMP_AI_API_KEY || "").trim();
  if (key) headers.set("X-InstaComp-AI-Key", key);

  try {
    const response = await fetch(`${baseUrl}/health`, {
      headers,
      cache: "no-store",
      redirect: "manual",
      signal: AbortSignal.timeout(20_000),
    });
    const health = (await response.json().catch(() => null)) as
      | Record<string, unknown>
      | null;

    if (!response.ok || !health) {
      return readinessJson(
        {
          ok: false,
          configured: true,
          reachable: true,
          dnsResolved: true,
          internalMemoryReady: false,
          checklistReady: false,
          localModelReady: false,
          runtimeSourceFingerprint: null,
          architecture: ["instacomp_ai"],
          reason: `internal_health_http_${response.status}`,
        },
        503,
      );
    }

    const internalMemoryReady = health.database === "ready";
    const checklistReady = health.checklist === "ready";
    const localModelReady = internalMemoryReady && checklistReady;
    return readinessJson(
      {
        ok: localModelReady,
        configured: true,
        reachable: true,
        dnsResolved: true,
        internalMemoryReady,
        checklistReady,
        localModelReady,
        app: typeof health.app === "string" ? health.app : "InstaComp AI",
        version: typeof health.version === "string" ? health.version : null,
        runtimeSourceFingerprint: null,
        architecture: ["instacomp_ai"],
        reason: localModelReady ? null : "internal_engine_not_fully_ready",
      },
      localModelReady ? 200 : 503,
    );
  } catch (error) {
    const name = error instanceof Error ? error.name : "unknown";
    return readinessJson(
      {
        ok: false,
        configured: true,
        reachable: false,
        dnsResolved: true,
        internalMemoryReady: false,
        checklistReady: false,
        localModelReady: false,
        runtimeSourceFingerprint: null,
        architecture: ["instacomp_ai"],
        reason:
          name === "TimeoutError" || name === "AbortError"
            ? "internal_engine_health_timeout"
            : "internal_engine_health_unreachable",
        networkErrorName: name,
      },
      503,
    );
  }
}

function fieldMatches(value: number, field: string, sundayAlias = false): boolean {
  return field.split(",").some((rawPart) => {
    const part = rawPart.trim();
    if (part === "*") return true;

    const stepMatch = /^\*\/(\d+)$/.exec(part);
    if (stepMatch) {
      const step = Number(stepMatch[1]);
      return Number.isInteger(step) && step > 0 && value % step === 0;
    }

    const rangeMatch = /^(\d+)-(\d+)(?:\/(\d+))?$/.exec(part);
    if (rangeMatch) {
      const start = Number(rangeMatch[1]);
      const end = Number(rangeMatch[2]);
      const step = Number(rangeMatch[3] ?? "1");
      if (!Number.isInteger(step) || step <= 0 || value < start || value > end) return false;
      return (value - start) % step === 0;
    }

    if (/^\d+$/.test(part)) {
      const exact = Number(part);
      if (sundayAlias && exact === 7) return value === 0;
      return value === exact;
    }

    throw new Error(`Unsupported cron field: ${field}`);
  });
}

const WEEKDAY_INDEX: Record<string, number> = {
  Sun: 0,
  Mon: 1,
  Tue: 2,
  Wed: 3,
  Thu: 4,
  Fri: 5,
  Sat: 6,
};

function cronDateParts(date: Date, timeZone?: string) {
  if (!timeZone) {
    return {
      minute: date.getUTCMinutes(),
      hour: date.getUTCHours(),
      dayOfMonth: date.getUTCDate(),
      month: date.getUTCMonth() + 1,
      dayOfWeek: date.getUTCDay(),
    };
  }

  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone,
    hourCycle: "h23",
    minute: "2-digit",
    hour: "2-digit",
    day: "2-digit",
    month: "2-digit",
    weekday: "short",
  }).formatToParts(date);
  const values = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  const dayOfWeek = WEEKDAY_INDEX[values.weekday];
  if (dayOfWeek === undefined) {
    throw new Error(`Unsupported weekday from timezone formatter: ${values.weekday}`);
  }

  return {
    minute: Number(values.minute),
    hour: Number(values.hour),
    dayOfMonth: Number(values.day),
    month: Number(values.month),
    dayOfWeek,
  };
}

function cronMatches(schedule: string, date: Date, timeZone?: string): boolean {
  const fields = schedule.trim().split(/\s+/);
  if (fields.length !== 5) {
    throw new Error(`Unsupported cron schedule: ${schedule}`);
  }

  const [minute, hour, dayOfMonth, month, dayOfWeek] = fields;
  const clock = cronDateParts(date, timeZone);
  return (
    fieldMatches(clock.minute, minute) &&
    fieldMatches(clock.hour, hour) &&
    fieldMatches(clock.dayOfMonth, dayOfMonth) &&
    fieldMatches(clock.month, month) &&
    fieldMatches(clock.dayOfWeek, dayOfWeek, true)
  );
}

async function runCronRoute(env: WorkerEnv, path: string): Promise<void> {
  if (!env.CRON_SECRET) {
    throw new Error("CRON_SECRET is not configured in the Cloudflare Worker.");
  }

  const request = new Request(new URL(path, "https://truelycollectables.internal"), {
    method: "GET",
    headers: {
      Authorization: `Bearer ${env.CRON_SECRET}`,
      "User-Agent": "truely-collectables-cloudflare-cron/1.0",
      "X-TCOS-Scheduler": "cloudflare",
    },
  });

  const response = await env.WORKER_SELF_REFERENCE.fetch(request);
  if (!response.ok) {
    const body = (await response.text().catch(() => "")).slice(0, 500);
    throw new Error(`Cron route ${path} returned ${response.status}: ${body}`);
  }
}

const worker = {
  async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContextLike) {
    const url = new URL(request.url);
    if (
      request.method === "GET" &&
      url.pathname === "/api/instacomp/internal-readiness"
    ) {
      return cloudflareInstaCompReadiness(env);
    }

    return withCloudflareOrigin(await handler.fetch(request, env, ctx));
  },

  async scheduled(
    controller: ScheduledControllerLike,
    env: WorkerEnv,
    _ctx: ExecutionContextLike,
  ) {
    void _ctx;
    if (INCIDENT_DISABLE_SCHEDULED_JOBS) {
      console.warn("Cloudflare scheduler paused during storefront database incident.");
      return;
    }

    const scheduledAt = new Date(controller.scheduledTime);
    const dueJobs = cronJobs.filter((job) =>
      cronMatches(job.schedule, scheduledAt, job.timeZone),
    );

    if (dueJobs.length === 0) return;

    const results = await Promise.allSettled(
      dueJobs.map((job) => runCronRoute(env, job.path)),
    );

    const failures = results
      .map((result, index) => ({ result, job: dueJobs[index] }))
      .filter(
        (entry): entry is { result: PromiseRejectedResult; job: (typeof dueJobs)[number] } =>
          entry.result.status === "rejected",
      );

    if (failures.length > 0) {
      for (const failure of failures) {
        console.error("Cloudflare cron dispatch failed", {
          path: failure.job.path,
          schedule: failure.job.schedule,
          reason:
            failure.result.reason instanceof Error
              ? failure.result.reason.message
              : String(failure.result.reason),
        });
      }
      throw new Error(`${failures.length} Cloudflare cron job(s) failed.`);
    }
  },
};

export default worker;
