import { timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";
import { analyzeWithInstaCompAiLocal } from "../../../../../lib/instacomp-ai-local";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 300;
const BUCKET_PATH = "/storage/v1/object/public/truely-product-images/collx-mirror/";
function json(payload: unknown, status=200){return NextResponse.json(payload,{status,headers:{"Cache-Control":"private, no-store, max-age=0","X-Content-Type-Options":"nosniff"}})}
function same(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&x.length>0&&timingSafeEqual(x,y)}
function auth(req:Request){const e=String(process.env.INSTACOMP_ACCEPTANCE_SERVICE_TOKEN||"").trim(),p=String(req.headers.get("x-tcos-instacomp-service-token")||"").trim();if(!e||!same(e,p))throw new Error("AUTH")}
function owned(v:unknown){const raw=String(v||"").trim();const u=new URL(raw),s=new URL(String(process.env.NEXT_PUBLIC_SUPABASE_URL||""));if(u.protocol!=="https:"||u.hostname!==s.hostname||!u.pathname.startsWith(BUCKET_PATH))throw new Error("OWNED_IMAGE_URL_REJECTED");return u.toString()}
async function file(url:string,name:string){const r=await fetch(url,{cache:"no-store",redirect:"error",signal:AbortSignal.timeout(30000)}),type=String(r.headers.get("content-type")||"").toLowerCase();if(!r.ok||!type.startsWith("image/"))throw new Error(`${name.toUpperCase()}_FETCH_${r.status}`);return new File([Buffer.from(await r.arrayBuffer())],`${name}.jpg`,{type})}
function ident(v:unknown){if(!v||typeof v!=="object"||Array.isArray(v))return null;const s=v as Record<string,unknown>,keys=["sport","league","year","manufacturer","brand","set_name","subset","player","team","card_number","parallel","variation","serial_number","serial_run","rookie","autograph","inscription","memorabilia"];return Object.fromEntries(keys.filter(k=>s[k]!==undefined).map(k=>[k,s[k]]))}
export async function POST(req:Request){try{auth(req);const b=await req.json(),cid=String(b?.collx_id||"").trim();if(!/^\d+$/.test(cid))return json({ok:false,code:"COLLX_ID_REQUIRED"},400);const fu=owned(b?.front_url),bu=owned(b?.back_url),[front,back]=await Promise.all([file(fu,"front"),file(bu,"back")]);const scan=await analyzeWithInstaCompAiLocal({front,back,timeoutMs:240000});const lv=scan.local_vision&&typeof scan.local_vision==="object"?scan.local_vision as Record<string,unknown>:{};return json({ok:true,schema:"tcos.collx.instacompPairedRetry.v1",collx_id:cid,front_url:fu,back_url:bu,status:scan.status,scan_id:scan.scan_id,card_uuid:scan.card_uuid||null,match_source:scan.match_source||null,visual_match_score:scan.visual_match_score??null,trusted_identity:ident(scan.trusted_identity),local_suggestion:scan.local_suggestion?{provider:String(scan.local_suggestion.provider||""),model:String(scan.local_suggestion.model||""),confidence:Number(scan.local_suggestion.confidence||0),identity:ident(scan.local_suggestion.identity)}:null,deterministic_identity_hints:ident(lv.identity_hints),checklist:{outcome:String(scan.checklist?.outcome||""),identity_id:scan.checklist?.identity_id||null,candidate_count:Number((scan.checklist as Record<string,unknown>|undefined)?.candidate_count||0),reasons:Array.isArray(scan.checklist?.reasons)?scan.checklist.reasons.slice(0,50):[]},next_action:String(scan.next_action||"").slice(0,1000),inventoryMutation:false,pricingMutation:false,publishingMutation:false})}catch(e){const m=e instanceof Error?e.message:"UNKNOWN";return json({ok:false,code:m==="AUTH"?"ACCEPTANCE_AUTH_REJECTED":"COLLX_PAIRED_RETRY_FAILED",error:m.slice(0,500)},m==="AUTH"?401:502)}}
