import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { importChecklistArtifact } from "../../src/lib/checklist-registry/server";
import type { ChecklistImportPlan, ChecklistSourceArtifact } from "../../src/lib/checklist-registry/source-adapter";
import { persistPlanManagement, preflightReleaseManagement } from "./management-staged-registry-writer.mjs";

const CATEGORY = "https://upperdeck.com/checklist-category/hockey/";
const START = new Date("2021-07-01T00:00:00Z");
const OUTPUT = resolve(process.env.UPPER_DECK_PRODUCTION_RECEIPT || ".upper-deck-recovery/production.json");
const DELAY_MS = Math.max(0, Number(process.env.UPPER_DECK_PRODUCTION_DELAY_MS || 3000));
const ATTEMPTS = Math.max(1, Number(process.env.UPPER_DECK_PRODUCTION_ATTEMPTS || 5));
const sleep = (ms:number)=>new Promise(r=>setTimeout(r,ms));
const transient=(m:unknown)=>/timeout|timed out|too many connections|connection terminated|connection reset|connection refused|could not query the database|web server is down|ssl handshake|\b50[0234]\b|\b52[125]\b|\b544\b|fetch failed|network|aborted|temporar|lock timeout/i.test(String(m||""));

function canonical(value:string,base:string){const url=new URL(value,base);url.hash="";url.search="";if(!url.pathname.endsWith("/"))url.pathname+="/";return url.toString();}
function stripTags(value:string){return value.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/\s+/g," ").trim();}
function parsedDate(value:string|null|undefined){if(!value)return null;const t=Date.parse(value);return Number.isFinite(t)?new Date(t):null;}
function publishedAtFromBlock(block:string){const dt=block.match(/<time\b[^>]*\bdatetime=["']([^"']+)["']/i)?.[1];const p=parsedDate(dt);if(p)return p.toISOString();const text=stripTags(block);const human=text.match(/\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+20\d{2}\b/i)?.[0];return parsedDate(human)?.toISOString()||null;}
function yearHint(url:string){const s=new URL(url).pathname.toLowerCase();const m=s.match(/(?:^|[^0-9])(20\d{2})(?:-(?:20)?\d{2})?(?:[^0-9]|$)/);return m?Number(m[1]):null;}
async function fetchHtml(url:string){let last:unknown=null;for(let attempt=1;attempt<=5;attempt++){try{const r=await fetch(url,{headers:{Accept:"text/html,application/xhtml+xml","User-Agent":"TCOS-InstaComp-UD-Recovery/1.0"},redirect:"follow",signal:AbortSignal.timeout(60_000)});if(!r.ok)throw new Error(`HTTP ${r.status} ${r.statusText}`);const text=await r.text();if(text.length<1000)throw new Error(`short HTML ${text.length}`);return text;}catch(e){last=e;if(attempt<5)await sleep(2000*attempt);}}throw last;}
async function discover(){const found=new Map<string,{url:string,publishedAt:string|null}>();for(let page=1;page<=40;page++){const pageUrl=page===1?CATEGORY:`${CATEGORY}page/${page}/`;let html:string;try{html=await fetchHtml(pageUrl);}catch(e){if(page>1&&/404/.test(String(e)))break;throw e;}const blocks=[...html.matchAll(/<article\b[\s\S]*?<\/article>/gi)].map(m=>m[0]);const sources:string[]=[];if(blocks.length){for(const block of blocks)for(const m of block.matchAll(/<a\b[^>]*href=["']([^"']+)["']/gi))try{const u=canonical(m[1],pageUrl);if(/^https:\/\/(?:www\.)?upperdeck\.com\/checklist\/[^/]+\/$/i.test(u)){sources.push(u);const pub=publishedAtFromBlock(block);const yh=yearHint(u);if((yh??9999)>=2021&&(!pub||new Date(pub)>=START))found.set(u,{url:u,publishedAt:pub});break;}}catch{}}else{for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["']/gi))try{const u=canonical(m[1],pageUrl);if(!/^https:\/\/(?:www\.)?upperdeck\.com\/checklist\/[^/]+\/$/i.test(u))continue;const i=m.index||0;const near=html.slice(Math.max(0,i-3000),Math.min(html.length,i+3000));const pub=publishedAtFromBlock(near);const yh=yearHint(u);if((yh??9999)>=2021&&(!pub||new Date(pub)>=START))found.set(u,{url:u,publishedAt:pub});}catch{}}if(!sources.length&&page>1)break;}return [...found.values()];}
function canonicalizePlan(plan:ChecklistImportPlan):ChecklistImportPlan{const norm=(v:unknown)=>String(v??"").trim().toLowerCase().replaceAll("&"," and ").replace(/[^\p{L}\p{N}/]+/gu," ")||null;const by=new Map<string,any>(),alias=new Map<string,string>(),configs=new Map<string,Set<string>>(),parallels:any[]=[];for(const p of plan.parallels||[]){const k=JSON.stringify([String(p.setSourceKey||""),norm(p.name),Number(p.serialRun||0)]);if(!configs.has(k))configs.set(k,new Set());configs.get(k)!.add(String(p.configurationExclusivity||""));if(!by.has(k)){const kept={...p};by.set(k,kept);alias.set(String(p.sourceKey),String(p.sourceKey));parallels.push(kept);}else alias.set(String(p.sourceKey),String(by.get(k).sourceKey));}for(const p of parallels){const k=JSON.stringify([String(p.setSourceKey||""),norm(p.name),Number(p.serialRun||0)]);if((configs.get(k)?.size||0)>1)p.configurationExclusivity=null;}const identities:any[]=[];const seen=new Set<string>();for(const i of plan.identities||[]){const x={...i,parallelSourceKey:i.parallelSourceKey?(alias.get(String(i.parallelSourceKey))||i.parallelSourceKey):null};const fk=`${x.fingerprint?.schema||""}|${x.fingerprint?.fingerprintSha256||""}`;if(seen.has(fk))continue;seen.add(fk);identities.push(x);}return {...plan,parallels,identities,validation:{...plan.validation,counts:{...plan.validation.counts,parallels:parallels.length,identities:identities.length}}};}
async function retry<T>(label:string,fn:()=>Promise<T>){let last:unknown=null;for(let attempt=1;attempt<=ATTEMPTS;attempt++){try{return await fn();}catch(e){last=e;console.warn(`${label} attempt ${attempt}/${ATTEMPTS}: ${e instanceof Error?e.message:String(e)}`);if(attempt===ATTEMPTS||!transient(e))break;await sleep(Math.min(30000,5000*attempt));}}throw last;}

async function main(){mkdirSync(dirname(OUTPUT),{recursive:true});const candidates=await discover();if(candidates.length<150)throw new Error(`Expected complete Upper Deck 2021+ census, got ${candidates.length}`);const receipt:any={schema:"tcos.upperDeckHockeyProductionRecovery.v1",updatedAt:new Date().toISOString(),candidateCount:candidates.length,results:[]};const save=()=>{receipt.updatedAt=new Date().toISOString();receipt.alreadyLiveCount=receipt.results.filter((r:any)=>r.status==="already_live").length;receipt.persistedCount=receipt.results.filter((r:any)=>r.status==="persisted").length;receipt.liveCount=receipt.results.filter((r:any)=>["already_live","persisted"].includes(r.status)).length;receipt.failedCount=receipt.results.filter((r:any)=>["failed","validation_failed","postflight_failed"].includes(r.status)).length;receipt.unresolvedCount=candidates.length-receipt.liveCount;writeFileSync(OUTPUT,JSON.stringify(receipt,null,2));};
for(let index=0;index<candidates.length;index++){const candidate=candidates[index];let row:any={index:index+1,sourceUrl:candidate.url,publishedAt:candidate.publishedAt,status:"failed"};try{const content=await fetchHtml(candidate.url);const artifact:ChecklistSourceArtifact={sourceUrl:candidate.url,originalFilename:`${new URL(candidate.url).pathname.split('/').filter(Boolean).at(-1)}.html`,mimeType:"text/html",content,retrievedAt:new Date().toISOString(),authority:"official_manufacturer",redistributionAllowed:false};const parsed=await importChecklistArtifact({artifact,validateOnly:true});const plan=canonicalizePlan(parsed.plan);row={...row,adapter:parsed.adapter,release:plan.release,counts:plan.validation.counts};const errors=plan.validation.issues.filter(x=>x.severity==="error");if(errors.length){row.status="validation_failed";row.errors=errors.slice(0,50);}else{const slug=String(plan.release.releaseSlug||"");if(!slug)throw new Error("Validated Upper Deck plan is missing releaseSlug");const pre=await retry(`preflight ${slug}`,()=>preflightReleaseManagement(slug));if((pre as any)?.complete){row.status="already_live";row.preflight=pre;}else{const persistence=await retry(`persist ${slug}`,()=>persistPlanManagement(plan,Buffer.from(content,"utf8")));const post=await retry(`postflight ${slug}`,()=>preflightReleaseManagement(slug));row.persistence=persistence;row.postflight=post;if(!(post as any)?.complete){row.status="postflight_failed";row.error=`Postflight did not find a complete active version for ${slug}`;}else row.status="persisted";}}}catch(e){row.status="failed";row.error=e instanceof Error?e.message:String(e);}receipt.results.push(row);save();console.log(`[${index+1}/${candidates.length}] ${row.status} ${candidate.url}`);if(index+1<candidates.length&&DELAY_MS)await sleep(DELAY_MS);}save();console.log(JSON.stringify({candidateCount:receipt.candidateCount,liveCount:receipt.liveCount,alreadyLiveCount:receipt.alreadyLiveCount,persistedCount:receipt.persistedCount,failedCount:receipt.failedCount,unresolvedCount:receipt.unresolvedCount},null,2));if(receipt.unresolvedCount!==0||receipt.failedCount!==0)process.exitCode=1;}
main().catch(e=>{console.error(e);process.exitCode=1;});
