const HOCKEY_CATEGORY_URL = "https://upperdeck.com/checklist-category/hockey/";
const START_DATE = new Date(process.env.HOCKEY_CHECKLIST_START_DATE || "2021-07-01T00:00:00Z");
const MIN_START_YEAR = 2021;
const MAX_CATEGORY_PAGES = Math.max(1, Math.min(50, Number(process.env.HOCKEY_CHECKLIST_MAX_CATEGORY_PAGES || 40)));

export type HockeyCandidate = { sourceUrl:string; publishedAt:string|null; categoryPage:number };

function canonical(value:string,base:string){const url=new URL(value,base);url.hash="";url.search="";if(!url.pathname.endsWith("/"))url.pathname+="/";return url.toString();}
function stripTags(value:string){return value.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/\s+/g," ").trim();}
function parsedDate(value:string|null|undefined){if(!value)return null;const time=Date.parse(value);return Number.isFinite(time)?new Date(time):null;}
function publishedAtFromBlock(block:string){const datetime=block.match(/<time\b[^>]*\bdatetime=["']([^"']+)["']/i)?.[1];const pd=parsedDate(datetime);if(pd)return pd.toISOString();const text=stripTags(block);const human=text.match(/\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+20\d{2}\b/i)?.[0];return parsedDate(human)?.toISOString()||null;}
function sourceStartYearHint(sourceUrl:string){try{const slug=new URL(sourceUrl).pathname.toLowerCase();const season=slug.match(/(?:^|[^0-9])(20\d{2})-(?:20)?\d{2}(?:[^0-9]|$)/);if(season)return Number(season[1]);const year=slug.match(/(?:^|[^0-9])(20\d{2})(?:[^0-9]|$)/);return year?Number(year[1]):null;}catch{return null;}}
function checklistUrlFromBlock(block:string,base:string){for(const match of block.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>/gi)){try{const url=canonical(match[1],base);const parsed=new URL(url);if(!/(^|\.)upperdeck\.com$/i.test(parsed.hostname))continue;if(/^\/checklist\/[^/]+\/$/i.test(parsed.pathname))return url;}catch{}}return null;}
function categoryEntries(html:string,base:string,categoryPage:number){const entries=new Map<string,HockeyCandidate>();for(const article of html.matchAll(/<article\b[\s\S]*?<\/article>/gi)){const block=article[0];const sourceUrl=checklistUrlFromBlock(block,base);if(!sourceUrl)continue;entries.set(sourceUrl,{sourceUrl,publishedAt:publishedAtFromBlock(block),categoryPage});}if(entries.size)return [...entries.values()];for(const match of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>/gi)){try{const sourceUrl=canonical(match[1],base);const parsed=new URL(sourceUrl);if(!/(^|\.)upperdeck\.com$/i.test(parsed.hostname))continue;if(!/^\/checklist\/[^/]+\/$/i.test(parsed.pathname))continue;const index=match.index||0;const nearby=html.slice(Math.max(0,index-3000),Math.min(html.length,index+3000));entries.set(sourceUrl,{sourceUrl,publishedAt:publishedAtFromBlock(nearby),categoryPage});}catch{}}return [...entries.values()];}

export async function fetchUpperDeckHtml(url:string){const response=await fetch(url,{headers:{Accept:"text/html,application/xhtml+xml","Cache-Control":"no-cache","User-Agent":"TCOS-Hockey-Checklist-Reconcile/1.0 (+private registry automation; contact sales@truelycollectables.com)"},redirect:"follow",signal:AbortSignal.timeout(60_000)});if(!response.ok)throw new Error(`HTTP ${response.status} ${response.statusText} fetching ${url}`);const type=response.headers.get("content-type")||"";if(!type.toLowerCase().includes("text/html"))throw new Error(`Unexpected content type ${type||"unknown"} fetching ${url}`);const html=await response.text();if(html.length<1000)throw new Error(`Incomplete HTML (${html.length} bytes) fetching ${url}`);return html;}

export async function discoverUpperDeckHockeyCandidates(){const candidates=new Map<string,HockeyCandidate>();const pages:any[]=[];for(let page=1;page<=MAX_CATEGORY_PAGES;page++){const pageUrl=page===1?HOCKEY_CATEGORY_URL:`${HOCKEY_CATEGORY_URL}page/${page}/`;let html:string;try{html=await fetchUpperDeckHtml(pageUrl);}catch(error){if(page>1&&/HTTP 404\b/i.test(error instanceof Error?error.message:String(error)))break;throw error;}const entries=categoryEntries(html,pageUrl,page);if(!entries.length)break;const dated=entries.map(e=>parsedDate(e.publishedAt)).filter((v):v is Date=>Boolean(v));const pageClearlyOld=dated.length>0&&dated.every(v=>v<START_DATE);const eligible=entries.filter(entry=>{const yearHint=sourceStartYearHint(entry.sourceUrl);if(yearHint!==null&&yearHint<MIN_START_YEAR)return false;const published=parsedDate(entry.publishedAt);if(published)return published>=START_DATE;return !pageClearlyOld;});for(const entry of eligible)candidates.set(entry.sourceUrl,entry);const times=dated.map(v=>v.getTime());pages.push({page,url:pageUrl,entryCount:entries.length,eligibleCount:eligible.length,newestPublishedAt:times.length?new Date(Math.max(...times)).toISOString():null,oldestPublishedAt:times.length?new Date(Math.min(...times)).toISOString():null});if(pageClearlyOld)break;}return {source:HOCKEY_CATEGORY_URL,boundary:START_DATE.toISOString(),candidates:[...candidates.values()],pages};}
