#!/usr/bin/env python3
from pathlib import Path

path = Path("services/instacomp-ai/app/apple_vision.py")
source = path.read_text(encoding="utf-8")

old = '''            self.bin_dir.mkdir(parents=True, exist_ok=True)\n            xcrun = shutil.which("xcrun") or "/usr/bin/xcrun"\n            temporary_binary = self.binary_path.with_suffix(".partial")\n            temporary_digest = self.digest_path.with_suffix(".partial")\n            command = [\n                xcrun,\n                "swiftc",\n                str(self.source_path),\n                "-O",\n                "-framework",\n                "Vision",\n                "-framework",\n                "AppKit",\n                "-framework",\n                "CoreGraphics",\n                "-o",\n                str(temporary_binary),\n            ]\n            completed = subprocess.run(\n                command,\n                check=False,\n                capture_output=True,\n                text=True,\n                timeout=120,\n            )\n            if completed.returncode != 0:\n                temporary_binary.unlink(missing_ok=True)\n                raise RuntimeError(\n                    "swiftc failed: "\n                    + (completed.stderr or completed.stdout or "unknown error")[-2000:]\n                )\n            temporary_binary.chmod(0o755)\n'''
new = '''            self.bin_dir.mkdir(parents=True, exist_ok=True)\n            swiftc = shutil.which("swiftc")\n            xcrun = shutil.which("xcrun")\n            if not swiftc and xcrun:\n                probe = subprocess.run(\n                    [xcrun, "--find", "swiftc"],\n                    check=False,\n                    capture_output=True,\n                    text=True,\n                    timeout=30,\n                )\n                candidate = probe.stdout.strip()\n                if probe.returncode == 0 and candidate and Path(candidate).is_file():\n                    swiftc = candidate\n            if not swiftc:\n                raise RuntimeError(\n                    "swiftc was not found. Install the Apple command-line developer tools."\n                )\n\n            temporary_binary = self.binary_path.with_name(\n                self.binary_path.name + ".partial"\n            )\n            temporary_digest = self.digest_path.with_name(\n                self.digest_path.name + ".partial"\n            )\n            temporary_binary.unlink(missing_ok=True)\n            temporary_digest.unlink(missing_ok=True)\n            command = [\n                swiftc,\n                str(self.source_path),\n                "-O",\n                "-framework",\n                "Vision",\n                "-framework",\n                "AppKit",\n                "-framework",\n                "CoreGraphics",\n                "-o",\n                str(temporary_binary),\n            ]\n            completed = subprocess.run(\n                command,\n                check=False,\n                capture_output=True,\n                text=True,\n                timeout=120,\n            )\n            if completed.returncode != 0 or not temporary_binary.is_file():\n                temporary_binary.unlink(missing_ok=True)\n                raise RuntimeError(\n                    "swiftc failed: "\n                    + (\n                        completed.stderr\n                        or completed.stdout\n                        or f"compiler exited {completed.returncode} without an output binary"\n                    )[-4000:]\n                )\n            temporary_binary.chmod(0o755)\n'''

if new in source:
    print(f"already fixed {path}")
    raise SystemExit(0)
if source.count(old) != 1:
    raise SystemExit("Apple Vision compiler block changed unexpectedly")
path.write_text(source.replace(old, new, 1), encoding="utf-8")
print(f"fixed {path}")
