import assert from 'node:assert/strict';
import { certifyControlPlane, type ControlDomain } from '../src/lib/kingmaker-phases-30-37-control-plane';
const domains:ControlDomain[]=['policy','identity','secrets','release','data','payments','fulfillment','recovery'];
const now='2026-08-03T19:00:00.000Z';
const good=domains.map((domain,i)=>({evidenceId:`e-${i}`,domain,observedAt:'2026-08-03T18:00:00.000Z',sourceVerified:true,controlPassed:true,ownerApproved:true,incidentOpen:false,artifactDigest:`sha256:${i}` }));
const base={evidence:good,now,maxEvidenceAgeDays:7,releaseCertified:true,accessCertified:true,rollbackReady:true,reconciliationComplete:true,killSwitchReady:true};
assert.equal(certifyControlPlane(base).verdict,'certified');
assert.equal(certifyControlPlane({...base,evidence:[...good,{...good[0]}]}).verdict,'blocked');
assert.equal(certifyControlPlane({...base,evidence:good.map((e,i)=>i===1?{...e,artifactDigest:good[0].artifactDigest}:e)}).verdict,'blocked');
assert.equal(certifyControlPlane({...base,evidence:good.map((e,i)=>i===2?{...e,observedAt:'2099-01-01T00:00:00.000Z'}:e)}).verdict,'review');
assert.equal(certifyControlPlane({...base,evidence:good.map((e,i)=>i===3?{...e,sourceVerified:false}:e)}).verdict,'quarantine');
assert.equal(certifyControlPlane({...base,evidence:good.map((e,i)=>i===4?{...e,incidentOpen:true}:e)}).verdict,'quarantine');
assert.equal(certifyControlPlane({...base,releaseCertified:false}).verdict,'blocked');
assert.equal(certifyControlPlane({...base,evidence:'hostile'}).verdict,'blocked');
assert.equal(certifyControlPlane({...base,now:'not-a-date'}).verdict,'blocked');
assert.equal(certifyControlPlane({...base,maxEvidenceAgeDays:Number.POSITIVE_INFINITY}).verdict,'blocked');
assert.equal(certifyControlPlane({...base,evidence:[...good.slice(0,7),{...good[7],domain:'rogue' as ControlDomain}]}).verdict,'quarantine');
const a=certifyControlPlane(base),b=certifyControlPlane({...base,evidence:[...good].reverse()});assert.equal(a.fingerprint,b.fingerprint);
console.log('KINGMAKER phases 30-37 control-plane regressions passed');
